[package]
name = "genome-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv="*"
serde_derive="*"
serde="*"
reqwest = {version = "*", features = ["blocking"]}
scraper = "*"
zip = "*"
